### ISSUE TITLE
Problem with import with version 5

### ISSUE THREAD

**Issue by majeeddl** [bpmn-io/bpmn-moddle#63]
I have follwing problem when I want import "bpmn-moddle".Please see problem

``` javascript
node_modules\bpmn-moddle\index.js:1
(function (exports, require, module, __filename, __dirname) { export {
                                                              ^^^^^^

SyntaxError: Unexpected token export

```

**Comment by pinussilvestrus** [comment]
Hi @majeeddl,
Maybe this will help you: https://github.com/bpmn-io/bpmn-moddle/issues/62. You will have to bundle your application to use it. Refer to the README.md to get more information (or just look inside the appending ticket).

I'll close this issue since there is no real bug described. In the future, feel free [to use our forum](https://forum.bpmn.io/).

**Comment by majeeddl** [comment]
Hi @pinussilvestrus , thanks a lot
